// Checks the payroll arithmetic of hr.js (attendance to paid days, PF, ESI, PT, overtime, net pay, the posting) without
// a browser:  node tools/hr-calc.js
'use strict';
const fs = require('fs'), path = require('path'), vm = require('vm');
const WEB = path.join(__dirname, '..', 'js');
let failures = 0;
function check(name, cond, detail) { if (cond) console.log('  ok   ' + name); else { failures++; console.log('  FAIL ' + name + (detail === undefined ? '' : '  -> ' + JSON.stringify(detail))); } }
const store = new Map();
const localStorage = { getItem: (k) => store.has(k) ? store.get(k) : null, setItem: (k, v) => store.set(k, String(v)), removeItem: (k) => store.delete(k) };
const ctx = { localStorage, console, setTimeout, clearTimeout, Blob: class {}, Response: class {} };
ctx.window = ctx; ctx.globalThis = ctx; ctx.App = { routes: {}, user: { id: 1 } }; ctx.UI = {}; ctx.Biz = { chargesGst: () => true }; ctx.Print = { table: () => '', show: () => {}, page: (t, c, m, body) => body, head: (t) => '<div>' + t + '</div>', signBlock: () => '', POWERED: '', PAPERS: { A4: { css: '' } } }; ctx.$ = () => null; ctx.$$ = () => []; ctx.icon = () => '';
vm.createContext(ctx);
['util.js', 'store.js', 'subscription.js', 'appformat.js', 'ledger.js', 'companies.js', 'hr.js'].forEach(f => vm.runInContext(fs.readFileSync(path.join(WEB, f), 'utf8'), ctx, { filename: f }));
const { Store, HR, Books } = ctx;
Store.open(1, '');

console.log('a month of attendance');
HR.saveSettings(Object.assign({}, HR.DEFAULTS, { ptState: 'Telangana', holidays: [{ date: '02/10/2026', name: 'Gandhi Jayanti' }] }));
const ravi = Store.add('employees', { code: 'EMP001', name: 'Ravi', doj: '01/04/2026', basic: 20000, da: 0, hra: 8000, conveyance: 1600, special: 2400, pf: true, esi: true, pt: true, tds: 500, active: true });
const meena = Store.add('employees', { code: 'EMP002', name: 'Meena', doj: '01/04/2026', basic: 10000, da: 2000, hra: 4000, conveyance: 1000, special: 1000, pf: true, esi: true, pt: true, tds: 0, active: true });
const def = HR.defaults('2026-10');
check('October 2026: Sundays are weekly offs, the 2nd a holiday, the rest working days', def[4] === 'W' && def[11] === 'W' && def[2] === 'H' && def[1] === 'P' && def[31] === 'P');
Store.add('attendance', { id: ravi.id + ':2026-10', empId: ravi.id, month: '2026-10', days: { 5: 'A', 6: 'A', 7: 'HD', 8: 'L' }, ot: { 30: 10 } });
const s = HR.summary(ravi, '2026-10');
check('summary: 2 absent, 1 half day, 1 leave, LOP 2.5, paid 28.5 of 31, overtime 10 h', s.A === 2 && s.HD === 1 && s.L === 1 && s.lop === 2.5 && s.paid === 28.5 && s.total === 31 && s.ot === 10, s);
check('hours: working days x 8 plus overtime', s.hours === (s.P * 8 + 4 + 10), s);
check('leave balance counts the leave of the financial year', JSON.stringify(HR.leaveBalance(ravi, '2026-10')) === JSON.stringify({ quota: 12, used: 1, left: 11 }), HR.leaveBalance(ravi, '2026-10'));

console.log('pay for the month');
const r = HR.compute(ravi, '2026-10');
const earn = (v) => Math.round(v * 28.5 / 31 * 100) / 100;
check('components earned per paid day', r.basic === earn(20000) && r.hra === earn(8000) && r.conv === earn(1600) && r.special === earn(2400), r);
check('gross is the sum', Math.abs(r.gross - (r.basic + r.hra + r.conv + r.special)) < 0.01, r.gross);
check('overtime: 10 h at 2x of 32000 / (26 x 8)', r.ot === Math.round(10 * (32000 / 208) * 2 * 100) / 100, r.ot);
check('PF on basic up to 15,000: employee 1,800, EPS 1,250, EPF 550', r.pfWage === 15000 && r.pfEmp === 1800 && r.eps === 1250 && r.epf === 550 && r.pfEmployer === 1800 && r.edli === 75 && r.pfAdmin === 75, r);
check('ESI: gross structure 32,000 is above the 21,000 ceiling, so none', r.esiEmp === 0 && r.esiEmployer === 0);
check('Telangana PT on ' + (r.gross + r.ot).toFixed(2) + ' is 200', r.pt === 200);
check('net = gross + OT - PF - PT - TDS', Math.abs(r.net - (r.gross + r.ot - 1800 - 200 - 500)) < 0.01, [r.net, r.gross, r.ot]);
const m = HR.compute(meena, '2026-10');
check('full attendance: 31 paid days, gross 18,000', m.paid === 31 && m.gross === 18000, m);
check('ESI within the ceiling: employee 135 (0.75% rounded up), employer 585', m.esiEmp === 135 && m.esiEmployer === 585, m);
check('PF on basic + DA 12,000: 1,440', m.pfWage === 12000 && m.pfEmp === 1440 && m.eps === Math.round(12000 * 8.33 / 100), m);
check('PT 150 in the 15,001-20,000 slab', m.pt === 150);
check('PT of a custom slab list', (HR.saveSettings(Object.assign(HR.settings(), { ptState: 'Custom slabs', ptSlabs: '10000:0, 20000:100, *:300' })), HR.ptOf(25000, HR.settings()) === 300 && HR.ptOf(15000, HR.settings()) === 100 && HR.ptOf(9000, HR.settings()) === 0));
HR.saveSettings(Object.assign(HR.settings(), { ptState: 'Telangana' }));

console.log('HRA and the Code on Wages');
check('HRA from basic: 40% outside a metro, 50% in one', HR.hraOf(20000, false) === 8000 && HR.hraOf(20000, true) === 10000);
const low = Store.add('employees', { code: 'EMP010', name: 'Low Basic', doj: '01/04/2026', basic: 10000, da: 0, hra: 12000, conveyance: 0, special: 8000, pf: true, esi: false, pt: false, tds: 0, active: true });
const lb = HR.compute(low, '2026-10');
check('basic + DA below half the pay: the shortfall counts as wages for PF', lb.wagesAdded === 5000 && lb.pfWage === 15000 && lb.pfEmp === 1800, lb);
Store.delete('employees', low.id);

console.log('hourly pay from timesheets');
const hourlyEmp = Store.add('employees', { code: 'EMP020', name: 'Hourly Hank', doj: '01/09/2026', payType: 'hourly', hourlyRate: 500, pf: false, esi: false, pt: true, tds: 0, active: true });
Store.add('timesheets', { id: hourlyEmp.id + ':2026-10-05', empId: hourlyEmp.id, week: '2026-10-05', hours: { 0: 9, 1: 9, 2: 9, 3: 9, 4: 9 }, approved: true });
Store.add('timesheets', { id: hourlyEmp.id + ':2026-09-28', empId: hourlyEmp.id, week: '2026-09-28', hours: { 0: 8, 1: 8, 2: 8, 3: 8 }, approved: false });
const hh = HR.hoursOf(hourlyEmp, '2026-10');
check('45 hours in a week: 40 regular + 5 overtime; a week starting in September counts its October day; the holiday on the 2nd pays 8 hours', hh.regular === 48 && hh.ot === 5 && hh.holiday === 8 && hh.unapproved === 1, hh);
Store.delete('timesheets', hourlyEmp.id + ':2026-09-28');
const hp = HR.compute(hourlyEmp, '2026-10');
check('pay = 48 h x 500 + 5 h x 500 x 1.5, PT on it, no PF / ESI', hp.basic === 24000 && hp.ot === 3750 && hp.pt === 200 && hp.pfEmp === 0 && hp.net === 24000 + 3750 - 200, hp);

console.log('reimbursements');
const rb = Store.add('reimbursements', { empId: ravi.id, date: '03/10/2026', category: 'Travel', amount: 1500, description: 'Taxi', status: 'approved' });
Store.add('reimbursements', { empId: ravi.id, date: '04/10/2026', category: 'Food', amount: 700, description: 'Lunch', status: 'pending' });
check('an approved claim is paid with the month, a pending one is not', HR.compute(ravi, '2026-10').reimb === 1500 && Math.abs(HR.compute(ravi, '2026-10').net - (r.net + 1500)) < 0.01);

console.log('the run and the posting');
let run = HR.computeRun('2026-10');
check('a run has a row per employee and the totals', run.rows.length === 3 && run.totals.net === Math.round((r.net + 1500 + m.net + hp.net) * 100) / 100 && run.status === 'draft', run.totals);
run.rows[1].advance = 1000; Store.add('payroll', run);
run = HR.computeRun('2026-10');
check('a recompute keeps the advance typed on a line', run.rows[1].advance === 1000 && run.rows[1].net === m.net - 1000, run.rows[1].net);
check('an employee who joined later is left out', (Store.add('employees', { code: 'EMP003', name: 'New', doj: '15/11/2026', basic: 5000, active: true }), HR.computeRun('2026-10').rows.length === 3));
run = HR.computeRun('2026-10'); run.status = 'final'; run.voucherId = HR.post(run); Store.update('payroll', run);
check('the claim shows as paid with the month once the run is final, without the claim being written; the pending one stays', HR.claimState(Store.find('reimbursements', rb.id)).status === 'paid' && HR.claimState(Store.find('reimbursements', rb.id)).paidMonth === '2026-10' && Store.find('reimbursements', rb.id).status === 'approved' && run.rows[0].reimbIds.includes(rb.id) && Store.list('reimbursements').some(x => HR.claimState(x).status === 'pending'));
check('a later month does not pay it again', HR.compute(ravi, '2026-11').reimb === 0);
check('reopening the month frees it', (run.status = 'draft', Store.update('payroll', run), HR.claimState(Store.find('reimbursements', rb.id)).status === 'approved' && HR.compute(ravi, '2026-11').reimb === 1500) && (run.status = 'final', Store.update('payroll', run), true));
const v = Store.find('journal', run.voucherId), t = run.totals;
const line = (a) => v.lines.find(l => l.account === a);
check('the voucher balances', Math.abs(v.lines.filter(l => l.side === 'Dr').reduce((x, l) => x + l.amount, 0) - v.lines.filter(l => l.side === 'Cr').reduce((x, l) => x + l.amount, 0)) < 0.01, v.lines);
check('salaries, reimbursements, employer share, the payables and the advance recovered', line('Salaries & Wages').amount === Math.round((t.gross + t.ot) * 100) / 100 && line('Staff Reimbursements').amount === 1500 && line('PF Payable').amount === t.pfEmp + t.pfEmployer + t.edli + t.pfAdmin && line('ESI Payable').amount === t.esiEmp + t.esiEmployer && line('Professional Tax Payable').amount === t.pt && line('TDS Payable').amount === t.tds && line('Staff Advances').amount === 1000 && line('Salary Payable').amount === t.net, v.lines);
check('the accounts were made with the right nature', Books.accounts().some(a => a.name === 'Salary Payable' && a.nature === Books.N.LIABILITY) && Books.accounts().some(a => a.name === 'Salaries & Wages' && a.nature === Books.N.EXPENSE));
const pl = Books.profitLoss(new Date(2026, 9, 1).getTime(), new Date(2026, 9, 31).getTime()), bs = Books.balanceSheet(new Date(2026, 9, 31).getTime());
check('salaries and reimbursements reach the Profit & Loss as expenses', Math.abs(pl.expenses - (t.gross + t.ot + t.reimb + t.pfEmployer + t.edli + t.pfAdmin + t.esiEmployer)) < 0.01, pl.expenses);
check('the payables sit on the Balance Sheet', bs.liabilities.some(l => l[0] === 'Salary Payable' && Math.abs(l[1] - t.net) < 0.01), bs.liabilities);
check('the records sync as HR rows', Object.keys(ctx.AppFormat.snapshot()).filter(k => /^(emp|att|ts|rb|pay):|^hr$/.test(k)).length === 4 + 1 + 1 + 2 + 1 + 1);
const slip = HR.payslipHtml(run, run.rows[0]);
check('the payslip has the employee details block, earnings and deductions side by side, the words at the foot and no row count', slip.includes('class="grid emp"') && slip.includes('Employee code') && slip.includes('EARNINGS') && slip.includes('DEDUCTIONS') && slip.includes('Net pay in words') && slip.includes('UAN (PF)') && slip.includes('Reimbursements') && !/\d+ rows?\./.test(slip) && !slip.includes('parties'));
console.log('who approves');
const boss = Store.add('employees', { code: 'EMP030', name: 'Boss', doj: '01/04/2026', basic: 50000, email: 'boss@example.com', active: true });
const lead = Store.add('employees', { code: 'EMP031', name: 'Lead', doj: '01/04/2026', basic: 30000, phone: '9000000001', managerId: boss.id, active: true });
const junior = Store.add('employees', { code: 'EMP032', name: 'Junior', doj: '01/04/2026', basic: 20000, managerId: lead.id, active: true });
ctx.Companies.role = () => 'hr';
ctx.App.user = { id: 1, name: 'Lead', phone: '9000000001' };
check('the login is matched to its employee record by mobile', HR.myEmployee() && HR.myEmployee().id === lead.id);
check('a reporting manager (HR role) approves for their report, not for themselves or their boss', HR.canApprove(junior) && !HR.canApprove(lead) && !HR.canApprove(boss) && HR.relation(junior) === 'manager' && HR.relation(lead) === 'self');
ctx.App.user = { id: 1, name: 'Boss', email: 'BOSS@example.com' };
check('the manager\'s manager approves too (two levels up, matched by email)', HR.canApprove(junior) && HR.canApprove(lead) && !HR.canApprove(boss));
ctx.Companies.role = () => 'admin';
check('an admin approves for anyone but themselves', HR.canApprove(junior) && HR.canApprove(lead) && !HR.canApprove(boss));
ctx.Companies.role = () => 'owner';
check('the owner is never held to the self rule', HR.canApprove(boss));
ctx.App.user = { id: 1, name: 'Nobody' };
console.log('the Full access plans');
check('the trial has Full access, a plain yearly plan does not, a Full access plan does', (ctx.Store.set('registered_at', Date.now()), ctx.Sub.isFull()) && (ctx.Sub.applyPlan({ days: 365 }), !ctx.Sub.isFull()) && (ctx.Sub.applyPlan({ days: 365, full: true }), ctx.Sub.isFull() && ctx.Sub.fullUntil() === ctx.Sub.subscriptionUntil()));
check('the Full access plans are on the list with their prices', ctx.Sub.PLANS.filter(p => p.full).map(p => p.price).join() === '599,4999,7999' && ctx.Sub.planLabel(7).includes('HR'));
const offer = HR.offerLetterHtml(ravi, { date: '07/10/2026', place: 'Hyderabad', probation: 6, notice: 30, hours: '8 hours a day', manager: 'Asha', terms: ['Laptop provided.'] });
check('the offer letter carries the designation, the pay and the terms', offer.includes('OFFER OF EMPLOYMENT') && offer.includes('position of <b>Employee</b>') && offer.includes('Cost to company') && offer.includes('Laptop provided.') && offer.includes('probation of 6 months'));

console.log(failures ? '\n' + failures + ' FAILED' : '\nall passed');
process.exit(failures ? 1 : 0);
